name: "http"
version: "0.1.0"
config-version: 2
profile: "http"

macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

require-dbt-version: [">=1.8.0", "<3.0.0"]
